### ISSUE TITLE
Reactors not working as expected on react-native

### ISSUE THREAD

**Issue by quarkcore** [HenrikJoreteg/redux-bundler#18]
On react-native reactors seem to not get executed. On the web the same bundle works like a charm.

Would really help to clearify this issue, because this project is the best solution for decoupled code sharing between redux apps i have worked with so far.

i have no idea why this happens but try to do further investigation myself. anybody an idea?

**Comment by aulneau** [comment]
@quarkcore did you find a fix for this?

**Comment by quarkcore** [comment]
@aulneau actually not. the execution works now anyhow. it was some trouble with the log i guess.

right now it looks like the action i return doesnt get dispatched. do you run in similar issues?

**Comment by HenrikJoreteg** [comment]
Hey @quarkcore! Thanks for reporting this. Is it just never running the reactors?  

Without knowing exactly what's happening, (I really haven't used RN much, personally). If so, I'd suggest looking here: https://github.com/HenrikJoreteg/redux-bundler/blob/master/src/bundles/create-reactor-bundle.js#L66-L74

That's what actually will grab the reactor it's supposed to run and then dispatch it.

**Comment by quarkcore** [comment]
Hi @HenrikJoreteg,
it runs the reactor like i wrote above. my logger was misleading me on that one.

nonetheless the returned action never gets dispatched. the code snippet you are mentioning looks like a good starting point for debugging. 

thanks for the quick answer!

**Comment by HenrikJoreteg** [comment]
@quarkcore oh sorry I missed that. Do you mind sharing what you're returning from the reactor? Is it an action object? or does it call an action creator or what?

**Comment by quarkcore** [comment]
@HenrikJoreteg my plan is to share a whole bundle between a native and web app. so the return value of the reactor sits in the bundle directly. i tried to return in both ways without success.

there were problems (that should be solved) with window.requestIdleCallback on RN https://github.com/facebook/react-native/issues/9579 and thats what redux-bundler tries to use in its ric util. i inspect that further tommorow.

**Comment by quarkcore** [comment]
@HenrikJoreteg It was my fault! 
I didnt realized that the `reactionBundle` isnt composed by default. In react-native we need to use  `composeBundlesRaw(...bundles)`. Because for example the `debugBundle` kicks errors with react-native if remote debugging is off due to the use off extened console mehtods like `console.groupCollpase()`.

so problem solved. maybe if i can find some time im able to tune the `debugBundle` to work with react-native too. its likely to be an helpful feature. 
if so to do i will open an issue to discuss how we can solve that!
