### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by greggb** [HenrikJoreteg/redux-bundler#22]
If I opened a PR, would there be interest in some better error handling (maybe only in dev mode)? When I mess something up I only see errors like `slice does not exist on undefined` etc. A few checks could pinpoint these errors a little more specifically. 

I'll have time in a week or so to work on some projects, and I'd love to help out on this.

**Comment by HenrikJoreteg** [comment]
That'd be great, @greggb. But yeah, let's wrap em in   env production vhecjs. So they don't bloat the final build 👍

**Comment by HenrikJoreteg** [comment]
I'm just going to close this issue to clean up. Looking forward to what you come up with on this, though 👍

**Comment by greggb** [comment]
No worries, had less time than I thought over my break, but still planning to do this. Thanks!
