### ISSUE TITLE
When starting an App offline, state of `online` is still `true`

### ISSUE THREAD

**Issue by layflags** [HenrikJoreteg/redux-bundler#29]
https://github.com/HenrikJoreteg/redux-bundler/blob/9591bae010ffb20873ef1279e77f1e757233b6e4/src/bundles/online.js#L9

What about setting the online reducer default state to `navigator.onLine`?

**Comment by HenrikJoreteg** [comment]
Oops! Good catch, want to do a PR?

**Comment by HenrikJoreteg** [comment]
@layflags don't bother with the PR... i'm fixing it right now

**Comment by HenrikJoreteg** [comment]
fixed via https://github.com/HenrikJoreteg/redux-bundler/commit/ea18ac8e6d254e444d197586a87039814173b494
