### ISSUE TITLE
url bundle seems to be applied regardless

### ISSUE THREAD

**Issue by huygn** [HenrikJoreteg/redux-bundler#41]
Even though I didn't import `createUrlBundle`, it's selectors (and `popstate` listener) still applied & reflected using `localStorage.debug = true`

**Comment by HenrikJoreteg** [comment]
Hey @huygn. So yes, `composeBundles()` has a few things included (just for convenience, see here for the exact list: https://github.com/HenrikJoreteg/redux-bundler/blob/master/src/index.js#L30-L42). 

But if you want to start with nothing, just use `composeBundlesRaw()`. Hope that helps.

**Comment by huygn** [comment]
Thanks! my bad I wasn't aware of it 👍
