### ISSUE TITLE
Dependency `querystringify` is way to old

### ISSUE THREAD

**Issue by layflags** [HenrikJoreteg/redux-bundler#55]
Hi Henrik,

the dependency `querystringify` is set to 0.0.4, but the current version is 2.1.1 and has some important fixes applied, like e.g. `Convert plus signs to spaces` (see https://github.com/unshiftio/querystringify/issues/7) or `Prevent overriding of build-in properties by default` (see https://github.com/unshiftio/querystringify/pull/19)

Would you mind updating `querystringify` to 2.1.1?

**Comment by HenrikJoreteg** [comment]
just published `v25.0.0`, it includes this upgrade, thanks! https://github.com/HenrikJoreteg/redux-bundler/blob/master/docs/misc/changelog.md#change-log
