### ISSUE TITLE
Play nicely with redux-devtools

### ISSUE THREAD

**Issue by HenrikJoreteg** [HenrikJoreteg/redux-bundler#7]
There's a `devtools` branch showing the level of integration I'd like to support. But... the decorated store idea seems to cause issues for the devtools copose function. 

It's possible that if the enhancements to `store` we make were written as a store enhancer this would just work.

A lot of folks I know don't actually end up using redux devtools often because there's often a router that has conflicting state. For redux-bundler *all* URL state is handled in redux, which could potentially make the redux time travel debugging work really well with it. So, it'd be cool to get this sorted out.

**Comment by HenrikJoreteg** [comment]
@aulneau thanks for your willingness! I didn't spend a lot of time diagnosing it because I don't actually tend to use the redux dev-tools much. So, the first thing that needs to happen is just some investigation, I think.

**Comment by aulneau** [comment]
hmm okay so I've played around with it a bit and I have it _mostly_ working, however I seem to be getting an error now related to the `named-action.js` method where `const found = store.meta.unboundActionCreators[actionCreator]`, `meta` doesn't seem to exist.

![screen shot 2018-04-12 at 2 37 31 pm](https://user-images.githubusercontent.com/11803153/38699927-129692f6-3e5f-11e8-9890-6ec593b822b3.png)

**Comment by HenrikJoreteg** [comment]
Completed by @aulneau, merged and shipped in `21.1.0`: https://github.com/HenrikJoreteg/redux-bundler/pull/16
