### ISSUE TITLE
Error not reading page from redux-blundler package

### ISSUE THREAD

**Issue by darkalghul** [HenrikJoreteg/redux-bundler#72]
I was working on a new project with react but when I tried putting together my bundle configuration (this includes the routing) I get the following error.

`Cannot read property 'page' of null` on redux-bundler.js file.

Here is an example of my current configuration:
https://bit.ly/3aNzRNp

I have the same configuration on another project that use redux-blundler 25.0.0 but for my current project I'm using version 27.0.1

Any idea on where this problem is coming from?

**Comment by HenrikJoreteg** [comment]
I don't really have time to do right now but off of the top of my head... very likely there is no matching route returned by selectRoute for the current URL.

**Comment by HenrikJoreteg** [comment]
You have routes for `/page` and `/featured` but when the app starts up on `/` there are no routes that match. Change `/page` in bundles/routes to `/` and you should see a different error.

Feel free to re-open if you think there's still something amiss.
