### ISSUE TITLE
Some of documentation cannot be found

### ISSUE THREAD

**Issue by minhluuquang** [HenrikJoreteg/redux-bundler#75]
After reading the documentation pages, I found that there are some pages that are not available anymore.
Here are the list:

https://github.com/HenrikJoreteg/redux-bundler/blob/master/api/bundle.html (Learn exactly what bundles can do)
https://github.com/HenrikJoreteg/redux-bundler/blob/master/api/included-bundles.html (Learn about all the functionality available in the included bundles)
https://github.com/HenrikJoreteg/redux-bundler/blob/master/guides/patterns.html (See the patterns page for tips on how to organize your code, and do things like caching and routing)
It would be great if you can update these docs so the beginners like me can use the lib easier

**Comment by HenrikJoreteg** [comment]
Oops! These pages actually still exist, but there were some broken links at the bottom of the intro page. I've fixed that now: https://reduxbundler.com let me know if there was something else i missed. THanks!
